apiVersion: v1 # configuraciones... actualmente mas para el servicio de monitoreo
kind: ConfigMap
metadata:
  name: cv-config
  namespace: cuando-viene
data:
  # property-like keys; each key maps to a simple value
  mongo.dbhost: "mongodb://mongodb:27017"
  mongo.dbname: "cuando-viene"
---
kind: Service # servicio principal... punto de entrada.
apiVersion: v1
metadata:
  name: cuando-viene-service
  namespace: cuando-viene
spec:
  type: LoadBalancer
  selector:
    app: cuando-viene-main
  ports:
    - name: http
      port: 80
      targetPort: 3002
---  
kind: Service # servicio principal. Usadfo
apiVersion: v1
metadata:
  name: cuando-viene-main
  namespace: cuando-viene
spec:
  type: ClusterIP
  selector:
    app: cuando-viene-main
  ports:
    - name: service
      port: 3002
      targetPort: 3002
---
apiVersion: apps/v1 # cuando viene main
kind: Deployment
metadata:
  name: cuando-viene-main
  namespace: cuando-viene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuando-viene-main
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cuando-viene-main
    spec:
      containers:
        - name: c-main
          imagePullPolicy: Never
          image: cuando-viene_main:latest
          ports:
            - name: service
              containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 25
            failureThreshold: 5
            periodSeconds: 90  
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
              memory: 100Mi 
---
kind: Service # Servicio de monitoreo
apiVersion: v1
metadata:
  name: cuando-viene-monitoreo-ext
  namespace: cuando-viene
spec:
  type: LoadBalancer
  selector:
    app: cuando-viene-monitoreo
  ports:
    - name: http
      port: 80
      targetPort: 3003
---
kind: Service # Servicio de monitoreo
apiVersion: v1
metadata:
  name: cuando-viene-monitoreo
  namespace: cuando-viene
spec:
  type: ClusterIP
  selector:
    app: cuando-viene-monitoreo
  ports:
    - name: monitoreo
      port: 3003
      targetPort: 3003
---  
apiVersion: apps/v1 # monitoreo de cuando-viene
kind: Deployment
metadata:
  name: cuando-viene-monitoreo
  namespace: cuando-viene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuando-viene-monitoreo
  template:
    metadata:
      labels:
        app: cuando-viene-monitoreo
    spec:
      containers:
        - name: monitoreo
          imagePullPolicy: Never
          image: cuando-viene_monitoreo:latest
          ports:
            - name: service
              containerPort: 3003
          livenessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 25
            failureThreshold: 5
            periodSeconds: 90  
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
              memory: 100Mi      
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: cv-config
                  key: mongo.dbhost
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: cv-config
                  key: mongo.dbname        
---             
kind: Service # Servicio de lineas
apiVersion: v1
metadata:
  name: cuando-viene-lineas
  namespace: cuando-viene
spec:
  type: ClusterIP
  selector:
    app: cuando-viene-lineas
  ports:
    - name: monitoreo
      port: 3001
      targetPort: 3001
---
apiVersion: apps/v1 # cuando viene lineas deployment
kind: Deployment
metadata:
  name: cuando-viene-lineas
  namespace: cuando-viene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuando-viene-lineas
  template:
    metadata:
      labels:
        app: cuando-viene-lineas
    spec:
      containers:
        - name: c-main
          imagePullPolicy: Never
          image: cuando-viene_lineas:latest
          ports:
            - name: service
              containerPort: 3001
          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 25
            failureThreshold: 5
            periodSeconds: 90  
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
              memory: 100Mi
---
kind: Service # Servicio de paradas
apiVersion: v1
metadata:
  name: cuando-viene-paradas
  namespace: cuando-viene
spec:
  type: ClusterIP
  selector:
    app: cuando-viene-paradas
  ports:
    - name: monitoreo
      port: 3000
      targetPort: 3000              
---
apiVersion: apps/v1 # cuando viene paradas deployment
kind: Deployment
metadata:
  name: cuando-viene-paradas
  namespace: cuando-viene
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cuando-viene-paradas
  template:
    metadata:
      labels:
        app: cuando-viene-paradas
    spec:
      containers:
        - name: c-main
          imagePullPolicy: Never
          image: cuando-viene_paradas:latest
          ports:
            - name: service
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 25
            failureThreshold: 5
            periodSeconds: 90  
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 100m
              memory: 100Mi  